# -*- coding: utf-8 -*-
"""test_bank_account.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOBKC5wfPC6AnNKY3Li5FSwot6PW-BJx
"""

import unittest
from programme_module import BankAccount


class TestBankAccount(unittest.TestCase):

    def setUp(self):
        self.account = BankAccount("Daniil")

    # --- Тесты пополнения ---

    def test_deposit_positive(self):
        result = self.account.deposit(100)
        self.assertEqual(self.account.balance, 100)
        self.assertIn("Пополнение успешно", result)

    def test_deposit_zero(self):
        result = self.account.deposit(0)
        self.assertEqual(result, "Ошибка: сумма должна быть больше 0")

    def test_deposit_negative(self):
        result = self.account.deposit(-50)
        self.assertEqual(result, "Ошибка: сумма должна быть больше 0")

    # --- Тесты снятия ---

    def test_withdraw_success(self):
        self.account.deposit(200)
        result = self.account.withdraw(100)
        self.assertEqual(self.account.balance, 100)
        self.assertIn("Снятие успешно", result)

    def test_withdraw_insufficient_funds(self):
        result = self.account.withdraw(50)
        self.assertEqual(result, "Ошибка: недостаточно средств")

    def test_withdraw_zero(self):
        result = self.account.withdraw(0)
        self.assertEqual(result, "Ошибка: сумма должна быть больше 0")

    def test_withdraw_negative(self):
        result = self.account.withdraw(-10)
        self.assertEqual(result, "Ошибка: сумма должна быть больше 0")

    # --- Тест баланса ---

    def test_get_balance(self):
        self.account.deposit(300)
        result = self.account.get_balance()
        self.assertEqual(result, "Текущий баланс: 300")


if __name__ == '__main__':
    unittest.main()